version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - ./volumes/db:/data/db
    environment:
      MONGO_INITDB_DATABASE: myprofile
  server:
    image: osamaahmed/my-profile-server:latest
    depends_on:
      - mongo
    volumes:
      - ./src/assets:/my-profile/assets
    environment:
      NODE_ENV: development
      SERVER_URL: http://localhost:8080
      TYPEORM_URL: mongodb://mongo/myprofile
      TYPEORM_SYNCHRONIZE: 'true'
      TYPEORM_LOGGING: 'true'
  nginx:
    image: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
      - ./src/assets:/assets
    ports:
      - '8080:80'
    depends_on:
      - server
    command: /bin/bash -c "cat < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
